{% set name = "pysaml2" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysaml2-{{ version }}.tar.gz
  sha256: f36871d4e5ee857c6b85532e942550d2cf90ea4ee943d75eb681044bbc4f54f7

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
  run:
    - importlib-metadata >=1.7.0
    - importlib-resources
    - cryptography >=3.1
    - defusedxml
    - pyopenssl
    - python >=3.6
    - python-dateutil
    - pytz
    - requests >=2.0.0,<3.0.0
    - six
    - importlib_resources
    - xmlschema >=2.0.0,<3.0.0
    - setuptools

test:
  imports:
    - saml2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://idpy.org
  dev_url: https://github.com/IdentityPython/pysaml2
  summary: Python implementation of SAML Version 2 Standard
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
