{% set name = "pysaml2" %}
{% set version = "7.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pysaml2-{{ version }}.tar.gz
  sha256: bd1c3f3667807de61d70d8e5cf32618719d9dc1b91a6d16a291ef7a1eaa52fff

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
  run:
    - importlib-metadata >=1.7.0
    - importlib-resources
    - cryptography >=46.0.5
    - defusedxml
    - pyopenssl >=26.0.0
    - python >={{ python_min }}
    - python-dateutil
    - pytz
    - requests >=2.0.0,<3.0.0
    - six
    - importlib_resources
    - xmlschema >=2.0.0,<3.0.0
    - setuptools

test:
  imports:
    - saml2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://idpy.org
  dev_url: https://github.com/IdentityPython/pysaml2
  summary: Python implementation of SAML Version 2 Standard
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
